base/urls.py
from django.urls import path
from base.views import *

app_name = 'base'

urlpatterns = [
    path('', index, name='index'),
    path('contato/', contato, name='contato'),
]

petshop/urls.py
from django.contrib import admin
from django.urls import path, include
from base.views import *



urlpatterns = [
    path('', include('base.urls', namespace='base')),
    path('reserva/', include('reserva.urls', namespace='reserva')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('rest_api.urls', namespace='api')),
]

reserva/urls.py
from django.urls import path
from reserva.views import criar_reserva

app_name = 'reserva'

urlpatterns = [
    path('criar/', criar_reserva, name='criar_reserva'),
]

rest_api/urls.py
from django.urls import path

from rest_api.views import  AgendamentoModelViewSet, ContatoModelViewSet

from rest_framework.routers import SimpleRouter

app_name = 'rest_api'

router = SimpleRouter(trailing_slash=False)
router.register('agendamento', AgendamentoModelViewSet)
router.register('contatos', ContatoModelViewSet)

urlpatterns = [
    
]

urlpatterns += router.urls

base/models.py
from django.db import models
from django.conf import settings


class Contato(models.Model):
    nome = models.CharField(max_length=50)
    email = models.EmailField(max_length=75)
    mensagem = models.TextField()
    data = models.DateTimeField(verbose_name="Data Envio", auto_now_add=True)
    def str(self):
        return f'{self.nome} - {self.email}'
    class Meta:
        verbose_name = 'Formulário de Contato'
        verbose_name_plural = 'Formulários de Contatos'
        ordering = ['-data']

reserva/models.py
from django.db import models

class Reserva(models.Model):
    TAMANHO_OPCOES = (
        (0, 'Pequeno'),
        (1, 'Médio'),
        (2, 'Grande'),
    )
    TURNO_OPCOES = (
            ('manhã', 'Manhã'),
            ('tarde', 'Tarde'),
    )
    nome = models.CharField(verbose_name='Nome', max_length=50)
    email = models.EmailField(verbose_name='Email')
    nome_pet = models.CharField(verbose_name='Nome do Pet', max_length=50)
    data = models.DateField(verbose_name='Data', help_text='dd/mm/aaaa')
    turno = models.CharField(verbose_name='Turno', max_length=10, choices=TURNO_OPCOES)
    tamanho = models.IntegerField(verbose_name='Tamanho', choices=TAMANHO_OPCOES)
    observacoes = models.TextField(blank=True)

    def quantidade_reserva(self):
        return self.reservas.count()

    def str(self):
        return f'{self.nome}: {self.data} - {self.turno}'

    class Meta:
        verbose_name = "Reserva de Banho"
        verbose_name_plural = "Reservas de Banho"

rest_api/models.py
from django.db import models

# Create your models here.

base/forms.py
from django import forms
from base.models import Contato


class ContatoForm(forms.ModelForm):
    class Meta:
        model = Contato
        fields = ['nome', 'email', 'mensagem']

reserva/forms.py
from django import forms
from reserva.models import Reserva
from datetime import date

class ReservaForm(forms.ModelForm):

    """ def clean_date(self):
        form_date = self.cleaned_data["data"]
        today_date = date.today()
        if form_date < today_date:
            raise forms.ValidationError('OPS, a data informada é anterior a data de hoje')
        return form_date """

    def clean_date(self):
        data = self.cleaned_data["data"]
        hoje = date.today()
        if data < hoje:
            raise forms.ValidationError('OPS, a data informada é anterior a data de hoje')
        return data


    """ def clean_shift(self):
        form_date = self.cleaned_data["date"]
        form_shift = self.cleaned_data["turno"]
        baths_in_same_day_and_hour = Reserva.objects.filter(date=form_date, shift=form_shift).count()
        if baths_in_same_day_and_hour >= 4:
            raise forms.ValidationError(f'Ops esse horário já esta lotado, para o turno da {form_shift}')
        return form_shift """


    class Meta:
        model = Reserva
        fields = [
            'nome', 'email', 'nome_pet', 'data', 'turno',
             'tamanho', 'observacoes'
        ]
    

""" class ReservationForm(forms.ModelForm):

    def clean_date(self):
        form_date = self.cleaned_data["date"]
        today_date = date.today()
        if form_date < today_date:
            raise forms.ValidationError('OPS, a data informada é anterior a data de hoje')
        return form_date

    def clean_shift(self):
        form_date = self.cleaned_data["date"]
        form_shift = self.cleaned_data["shift"]
        baths_in_same_day_and_hour = Reservation.objects.filter(date=form_date, shift=form_shift).count()
        if baths_in_same_day_and_hour >= 4:
            raise forms.ValidationError(f'Ops esse horário já esta lotado, para o turno da {form_shift}')
        return form_shift

    class Meta:
        model = Reservation
        fields = "all" """

base/views.py
from django.shortcuts import render
from base.forms import ContatoForm

    
def index(request):
    return render(request, 'index.html')

def contato(request):
    sucesso = False
    form = ContatoForm(request.POST or None)
    if form.is_valid():
        sucesso = True
        form.save()
    contexto = {
        'telefone': '(71) 95555-5555',
        'responsavel': 'William Santos',
        'form': form,
        'sucesso': sucesso
    }
    return render(request, 'contato.html', contexto)

reserva/views.py
from django.shortcuts import render
from reserva.forms import ReservaForm

# Create your views here.
def criar_reserva(request):
    form = ReservaForm(request.POST or None)
    sucesso = False
    if form.is_valid():
        form.save()
        sucesso = True
    contexto = {
        'form': form,
        'sucesso': sucesso
    }
    return render(request, 'criar_reserva.html', contexto)

rest_api/views.py
from django.shortcuts import render

from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet

from reserva.models import Reserva
from base.models import Contato
from rest_api.serializers import AgendamentoModelSerializer, ContatoModelSerializer


# Create your views here.



class AgendamentoModelViewSet(ModelViewSet):
    queryset = Reserva.objects.all()
    serializer_class = AgendamentoModelSerializer
    
class ContatoModelViewSet(ModelViewSet):
    queryset = Contato.objects.all()
    serializer_class = ContatoModelSerializer

base/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <title>Blog Template · Bootstrap v5.0</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/blog/">
    <!-- Bootstrap core CSS -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<meta name="theme-color" content="#7952b3">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
  </head>
  <body>
    
<div class="container">
  <header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
        <a class="link-secondary" href="#">Subscribe</a>
      </div>
      <div class="col-4 text-center">
        <h1 class="blog-header-logo text-dark" href="#">Pet Online</h1>
      </div>
      <div class="col-4 d-flex justify-content-end align-items-center">
        <a class="link-secondary" href="#" aria-label="Search">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"/><path d="M21 21l-5.2-5.2"/></svg>
        </a>
        <a class="btn btn-sm btn-outline-secondary" href="#">Sign up</a>
      </div>
    </div>
  </header>

  <div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
      <a class="p-2 link-secondary" href="{% url 'base:index' %}">Inicio</a>
      <a class="p-2 link-secondary" href="{% url 'base:contato' %}">Contato</a>
      <a class="p-2 link-secondary" href="{% url 'reserva:criar_reserva' %}">Reserva</a>
    </nav>
  </div>
</div>

{% block conteudo %} {% endblock %}
  </div>
</main>

<footer class="blog-footer">
  <p class="text-center">Criado por William</p>
  
    
</footer>

  </body>
</html>

base/templates/contato.html
{% extends 'base.html' %}

{% load bootstrap5 %}

{% block conteudo %}
<main class="px-3">
  <div class="p-2 p-md-1 mb-4 text-white rounded bg-dark container">
    <div class="col-md-11px-0">
      <h4 class="display-11 fst-italic text-center">Fale conosco</h4>
      <p class="fst-italic text-center">
        Envie uma mensagem através do Formulário abaixo ou ligue para o telefone {{ telefone }}
        e fale com o responsável {{ responsavel|upper }}.
      </p>
    </div>
  </div>
  
      {% if sucesso %}
      <p class="alert alert-success fst-italic">Mensagem enviada com sucesso!</p>
      {% else %}
     <br>
     <form action="" method="post" novalidate class=" m-auto fst-italic container">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button class="btn btn-primary my-5 fst-italic" type="submit">Enviar Mensagem</button>
    </form>
    {% endif %}
</main>
{% endblock %} 

base/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block conteudo %}

<main class="container">
  <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
      <h1 class="display-4 fst-italic">Reserva já o banho de seu Pet!</h1>
      <p class="lead my-3">Demonstre seu amor por quem te ama de verdade!</p>
      <p class="lead mb-0"><a href="#" class="text-white fw-bold">Entrar <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-box-arrow-in-right" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0v-2z"/>
        <path fill-rule="evenodd" d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
      </svg></a></p>
    </div>
  </div>
{% endblock %}
     
      

reserva/templates/criar_reserva.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block conteudo %}
      <main>
        <div>
        {% if sucesso %}
        <p class="alert alert-success fst-italic">Reserva realizada com sucesso, em breve iremos entrar em contato!</p>
        {% else %}
        <br>
        <form action="" method="post" novalidate class="col-11 m-auto mt-md-1 fst-italic">
          <div class="p-2 p-md-1 mb-4 text-white rounded bg-dark">
            <div class="col-md-10 px-0">
              <h4 class="display-10 fst-italic text-center">Crie sua reserva no formulário abaixo</h4>
            </div>
          </div>
          {% csrf_token %}
          {% bootstrap_form form %}
            <button class="btn btn-primary my-5 fst-italic" type="submit">Agendar</button>
        </form>
        {% endif %}
      </div>
      </main>
{% endblock %}
      